### ISSUE TITLE
restore rancher backup

### ISSUE THREAD

**Issue by kilmarnock** [deitch/mysql-backup#10]
Hi!
I use your tool to create rancher db backups. 

Now I have a dumpfile, db_backup_20170215233157.gz.

I try to restore on a fresh rancher server install doing
`
docker run --link pedantic_torvalds:db  -e DB_RESTORE_TARGET=/backup/db_backup_20170215233157.gz  -v /mnt/stick:/backup deitch/mysql-backup                                         
`
It says:
`
ERROR 2013 (HY000) at line 823: Lost connection to MySQL server during query
`
and the container starts and stops forever. The `lost connection` happens in different lines if I try it again.

**Comment by deitch** [comment]
I don't see a `DB_USER` or `DB_PASS`. Maybe you should set `DB_DUMP_DEBUG=true` to see what the problem is?

**Comment by kilmarnock** [comment]
Thank you for your answer.
It turned out that the mysql service did not come up as it should.

**Comment by deitch** [comment]
That might do it!

I am glad it was that easy.

**Comment by kilmarnock** [comment]
Hi! 
I try the same as above:
`docker run --link nervous_newton:db -e DB_RESTORE_TARGET=/backup/db_backup_20170301115500.gz -e DB_DUMP_DEBUG=true -v /mnt/stick:/backup deitch/mysql-backup`
Result is: 
+ ...
+ cp /backup/db_backup_20170301115500.gz /tmp/restorefile
+ [[ -f /tmp/restorefile ]]
+ mysql -h db -u cattle -pcattle
+ gunzip
ERROR 2013 (HY000) at line 660: Lost connection to MySQL server during query
+ /bin/rm -f /tmp/restorefile
+ exit 0

```
FATAL: Exiting due to failed cluster check-in
2017-03-02 10:09:29,913 ERROR   [pool-2-thread-1] [ConsoleStatus] Check-in failed java.lang.IllegalStateException: Failed to update check-in, registration deleted
        at io.cattle.platform.hazelcast.membership.dao.impl.ClusterMembershipDAOImpl.checkin(ClusterMembershipDAOImpl.java:35) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.hazelcast.membership.DBDiscovery.checkin(DBDiscovery.java:169) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
        at io.cattle.platform.hazelcast.membership.DBDiscovery.doRun(DBDiscovery.java:158) ~[cattle-hazelcast-common-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.NoExceptionRunnable.runInContext(NoExceptionRunnable.java:15) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:49) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:108) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:46) [cattle-framework-managed-context-0.5.0-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_72]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_72]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_72]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_72]

time="2017-03-02T10:09:30Z" level=info msg="Exiting go-machine-service" 
time="2017-03-02T10:09:30Z" level=info msg="Exiting rancher-compose-executor" version=v0.12.2 
170302 10:09:31 [Note] /usr/sbin/mysqld (mysqld 5.5.53-0ubuntu0.14.04.1) starting as process 25 ...
Uptime: 2  Threads: 1  Questions: 2  Slow queries: 0  Opens: 35  Flush tables: 1  Open tables: 26  Queries per second avg: 1.000
Setting up database
```

**Comment by deitch** [comment]
That is strange. It is doing the right thing: copying the file to the right location, gunzip and piping to mysql command. The error itself `HY000 at line 660` is coming from mysql command.

Where is the ready of the output coming from? Is it from the rancher container?

**Comment by kilmarnock** [comment]
> Where is the ready of the output coming from?
You are talking about the stacktrace? This is from the rancher server container rancher/server:v1.4.1

**Comment by deitch** [comment]
Hmm... something to do with Rancher. Are you working on a clean restore, or is it a live version with data in it? Also, are you backing up from and restoring to the same version of Rancher?

**Comment by kilmarnock** [comment]
It is a fresh pulled image. I tried v1.4.1 -> v1.4.1 and  1.4.1-> 1.5.0rc1

**Comment by deitch** [comment]
Hmm, might need to ask @ibuildthecloud. This appears to be a Rancher issue, rather than a mysql-backup issue. The backup and restore are working as expected, but Rancher is crashing on database restore.

I suggest opening an issue there. If it turns out that how you restore to rancher has changed (it definitely _was_ "start a clean instance and use mysql to restore" but might have changed), then we can open a separate issue for adjusting to it, if it is generic enough.

**Comment by michalbehun** [comment]
Hello.
I have the same problem, but I can't find any solution all over the internet by myself.
@kilmarnock Did you create issue to rancher/rancher? Or come to some solution?

I also noticed that DB_SERVER variable is missing in RESTORE paragraph examples.
Thank you for answer.

**Comment by deitch** [comment]
That is a good point @michalbehun . Thanks.

I will close out this old issue, but fix those.
